#!/var/jb/usr/bin/sh
set -eu

. "$(dirname -- "$0")/common.sh"

source_script="$PROJECT_DIR/scripts/hotspot_clients.sh"
command_name=hotspot-clients

if [ ! -x "$source_script" ]; then
    echo "Source command is missing or not executable: $source_script" >&2
    exit 1
fi

if [ "$(id -u)" -eq 0 ]; then
    if [ -d /var/jb/usr/local/bin ] || [ -d /var/jb/usr ]; then
        bin_dir=/var/jb/usr/local/bin
    else
        bin_dir=/usr/local/bin
    fi
    profile_file=
else
    bin_dir=${HOME:-/var/mobile}/bin
    profile_file=${HOME:-/var/mobile}/.zprofile
fi

mkdir -p "$bin_dir"
destination="$bin_dir/$command_name"
generated_marker="# Generated by iphone-mjpeg install_hotspot_clients.sh"

if [ -L "$destination" ]; then
    if [ "$(readlink "$destination")" = "$source_script" ]; then
        # Repair the older symlink form. The command sources common.sh relative
        # to $0, so it needs a wrapper that preserves the real script path.
        rm "$destination"
    else
        echo "Refusing to replace unrelated symlink $destination" >&2
        exit 1
    fi
elif [ -e "$destination" ] && ! grep -Fqx "$generated_marker" "$destination"; then
    echo "Refusing to replace existing $destination" >&2
    exit 1
fi

temporary="$destination.tmp.$$"
trap 'rm -f "$temporary"' EXIT HUP INT TERM
{
    printf '%s\n' '#!/var/jb/usr/bin/sh'
    printf '%s\n' "$generated_marker"
    printf 'exec "%s" "$@"\n' "$source_script"
} >"$temporary"
chmod 755 "$temporary"
mv -f "$temporary" "$destination"
trap - EXIT HUP INT TERM
echo "Installed: $destination"

if [ -n "$profile_file" ]; then
    path_line='export PATH="$HOME/bin:$PATH"'
    if [ ! -f "$profile_file" ] || ! grep -Fqx "$path_line" "$profile_file"; then
        {
            printf '\n# iPhone Personal Hotspot client inspector\n'
            printf '%s\n' "$path_line"
        } >>"$profile_file"
        echo "Added $bin_dir to PATH in $profile_file"
    fi
    PATH="$bin_dir:$PATH"
    export PATH
fi

"$destination" --help >/dev/null
echo "Ready: $command_name"
